[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip']

[phases.install]
cmds = ['pip3 install -r requirements.txt']

[phases.build]
cmds = ['echo "No build step needed for FastAPI"']

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT'
