[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.virtualenv']

[phases.install]
cmds = [
  'python3 -m venv /opt/venv',
  '/opt/venv/bin/pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "No build step needed for FastAPI"']

[start]
cmd = '/opt/venv/bin/uvicorn main:app --host 0.0.0.0 --port $PORT'
